### ISSUE TITLE
creating a div wrapping component will break flexbox based layouts

### ISSUE THREAD

**Issue by luisrudge** [casesandberg/react-context#11]
[as seen here](https://github.com/casesandberg/react-context/blob/master/src/context.js#L220)

Since flexbox is applied to direct children, this will break components that use flexbox

**Comment by casesandberg** [comment]
Hmm, true. I am trying to think of an appropriate way to fix this, do you have any ideas?

**Comment by luisrudge** [comment]
no, no ideas.. sorry :|
