### ISSUE TITLE
It doesn't seem to recognize uBlock on safari.

### ISSUE THREAD

**Issue by casesandberg** [casesandberg/react-context#3]
https://news.ycombinator.com/item?id=9957109

**Comment by ktaube** [comment]
It doesn't seem recognise uBlock Origin 0.9.9.3 on chrome 44.0.2403.107 as well

**Comment by DiThi** [comment]
Neither on Firefox.

**Comment by danieljuhl** [comment]
Neither on Mac Chrome

**Comment by casesandberg** [comment]
Looks like its `FuckAdBlock`s script that doesnt support it yet. Going to close and watch that issue there until its fixed:

https://github.com/sitexw/FuckAdBlock/issues/44
