### ISSUE TITLE
debounce scroll and resize events

### ISSUE THREAD

**Issue by theverything** [casesandberg/react-context#4]
Firing the scroll and resize events constantly can be really bad for page perf.

On your example page you can see the page stutter when scrolling.

It would be nice if the events were [debounced](http://davidwalsh.name/javascript-debounce-function). Maybe with a optional config to set the debounce rate for each event when initializing.

**Comment by casesandberg** [comment]
Ah, my only concern with that was when someone wanted precise events for scroll or resize. Wouldnt it make sense for you to just debounce in your own component?

**Comment by danieljuhl** [comment]
I would vote for default debounce, but allowing to disable the debounce.. The problem, is that otherwise one would have to debounce all the places, where you listen for the context change.

**Comment by casesandberg** [comment]
I am going to close this as a `wontfix` because I dont want to pull in a lodash dependency just for debounce. It should be handled in your own project.
