### ISSUE TITLE
pass information via props

### ISSUE THREAD

**Issue by luisrudge** [casesandberg/react-context#9]
is there a way to pass all this info via props instead of state?

**Comment by casesandberg** [comment]
@luisrudge It kind of defeats the whole purpose though, does it not? You would then have to worry about passing the information down to all your child components, thats the whole point of using context.

**Comment by luisrudge** [comment]
I don't think so. You already have to worry about that today, because you have to actively use contextTypes to "ask" for information. That's why react-router, which was entirely based on context, moved to props.

**Comment by luisrudge** [comment]
Also, if anything, this info shouldn't be added to the component's state, since it's not part of the component state at all.
